blank_issues_enabled: false
contact_links:
  - name: ANTsX Issues (ANTsPy, ANTsR, ANTs*Net) 
    url: https://github.com/ANTsX
    about: If you are not working with base ANTs (ie, the command line tools), please go to the main ANTsX page and open an issue in the repository you are using. 
