# Workflow adapted from https://gist.github.com/NickNaso/0d478f1481686d5bcc868cac06620a60
# build directly on supported runners: Ubuntu 18, Ubuntu 20, Mac OS 11
name: Native release binaries

# Controls when the action will run. Triggers the workflow on push
on:
  release:
    types: [created]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu_20.04-GCC",
            os: ubuntu-20.04,
            artifact: "ubuntu-20.04-gcc.zip",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }
        - {
            name: "Ubuntu_18.04-GCC",
            os: ubuntu-18.04,
            artifact: "ubuntu-18.04-gcc.zip",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }
        - {
            name: "macos-11-clang",
            os: macos-11,
            artifact: "macos-11-clang.zip",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu_')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version
      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos-11')
        run: |
          brew install cmake ninja
          ninja --version
          cmake --version
      - name: Configure
        shell: bash
        working-directory: ${{ runner.temp }}
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}" \
            -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}/install/ants-${{ github.ref_name }} \
            ${GITHUB_WORKSPACE}
      - name: Build
        shell: bash
        working-directory: ${{ runner.temp }}
        run: |
          cd build
          cmake --build . --config ${{ matrix.config.build_type }} --parallel
      - name: Install
        shell: bash
        working-directory: ${{ runner.temp }}
        run: |
          cd build/ANTS-build
          cmake --install .
      - name: Pack
        shell: bash
        working-directory: ${{ runner.temp }}
        run: |
          cd install
          zip -r ${{ runner.temp }}/ants-${{ github.ref_name }}-${{ matrix.config.artifact }} .
      - name: Upload release asset
        # Previously was using actions/upload-release-asset@v1 , but this had some
        # errors with large files
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: "${{ runner.temp }}/ants-${{ github.ref_name }}-${{ matrix.config.artifact }}"
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}